name: Daily Crawl Update

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run crawler
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          JAWG_ACCESS_TOKEN: ${{ secrets.JAWG_ACCESS_TOKEN }}
        run: |
          # placeholder for crawler script
          node scripts/crawl.js || echo "Crawl script not implemented yet"
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update map data via crawler" || echo "No changes to commit"
          git push
