name: Generate QR Codes and Update Beacon Data

on:
  push:
    paths:
      - '**/TAK/beacons.txt'
  workflow_dispatch:

jobs:
  generate-qr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate QR Codes
        run: |
          pip install qrcode[pil]
          python scripts/generate_qr.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add QR codes for new beacons" || echo "No changes to commit"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "update-beacons"
          title: "Update Beacon Data and QR Codes"
          body: |
            This pull request updates the TAK directories with new QR codes and beacon data.
